Mending: Initial state of 0.4, revision 1

diff --git a/scripts/copysrc b/scripts/copysrc
--- a/scripts/copysrc
+++ b/scripts/copysrc
@@ -2,10 +2,10 @@
 
 # copies sources from CVS folder into given target folder
 
-set -x
+# set -x
 
 # read configuration
-. ./make.conf
+. make.conf
 
 TARGET=$1
 VERSION=$2
@@ -13,11 +13,15 @@ VERSION=$2
 # generate automatic files
 CWD=`pwd`
 if test -z "$VERSION"; then
-    # bootstrap
-    lwd=`pwd`
-    cd $AA_SOURCE
-    sh ./bootstrap.sh || exit -1
-    cd ${lwd}
+    if test -r $AA_SOURCE/version && test -r $AA_SOURCE/configure && test -r $AA_SOURCE/ChangeLog ; then
+        echo "No bootstrap required."
+    else
+        # bootstrap
+        lwd=`pwd`
+        cd $AA_SOURCE
+        sh ./bootstrap.sh || exit -1
+        cd ${lwd}
+    fi
         
     # adapt version to source
     VERSION=`sed -e 's,.*\[,,' -e 's,\].*,,'  < $AA_SOURCE/version`
@@ -37,16 +41,10 @@ fi
 mkdir -p $TARGET/distmaker
 lwd=`pwd`
 cd $TARGET/distmaker
-rm -rf armagetronad-*
-rm -rf ${PACKAGE}-*
-rm -f *.tar.*
-test -r config.h || progname="${PACKAGE}" progtitle="${PROGNAME}" CXXFLAGS="-O0" docstyle=web $CWD/$AA_SOURCE/configure --prefix=/usr/local --disable-glout --enable-automakedefaults --disable-useradd --disable-etc --disable-initscripts || exit -1
+test -r config.h || docstyle=web $CWD/$AA_SOURCE/configure --prefix=/usr/local --disable-glout --enable-automakedefaults --disable-useradd --disable-etc --disable-initscripts || exit -1
 ${MAKE} distprep || exit -1
 ${MAKE} dist || exit -1
-tar -xzf *.tar.*
-mv armagetronad-${VERSION} ${PACKAGE}-${VERSION}
-tar -cf ../${PACKAGE}-${VERSION}.src.tar ${PACKAGE}-${VERSION}
-#mv *.tar.* ../
+mv *.tar.* ../
 cd ${lwd}
 
 # copy raw sources for later tagging
