Merging branch 0.2.8 from revision 9765 to 9771:  ------------------------------------------------------------------------  r9771 | bazaaarmagetron | 2011-08-27 16:25:02 +0200 (Sat, 27 Aug 2011) | 2 lines
 Manuel Moos: Only put in very specific libjpeg version.
 
 ------------------------------------------------------------------------
 r9770 | bazaaarmagetron | 2011-08-27 16:24:35 +0200 (Sat, 27 Aug 2011) | 2 lines
 
 Manuel Moos: reverted accidental test change
 
 ------------------------------------------------------------------------
 r9769 | bazaaarmagetron | 2011-08-27 16:20:57 +0200 (Sat, 27 Aug 2011) | 2 lines
 
 Manuel Moos: Adding more libraries.
 
 ------------------------------------------------------------------------
 r9768 | bazaaarmagetron | 2011-08-27 16:20:28 +0200 (Sat, 27 Aug 2011) | 4 lines
 
 author: Manuel Moos
 Delegating portable app work into script.
 Putting needed libries into appdir so we don't have to link dynamically.
 
 ------------------------------------------------------------------------
 r9767 | bazaaarmagetron | 2011-08-27 13:04:09 +0200 (Sat, 27 Aug 2011) | 2 lines
 
 Manuel Moos: Properly uploading portable app.
 
 ------------------------------------------------------------------------

diff --git a/portable/build b/portable/build
--- a/portable/build
+++ b/portable/build
@@ -6,18 +6,11 @@
 #   add AppRun and desktop file
 cp portable/AppRun ${APPDIR}/
 find ${APPDIR} -name "*.desktop" -exec mv \{\} ${APPDIR}/ \;
-find ${APPDIR} -type l -name "*.desktop" -exec rm \{\} \;
 
 #   hack Icon
-for f in $(find ${APPDIR} -type d -name "desktop"); do
-  cp $f/icons/small/*.png ${APPDIR}/${PACKAGE}.png
-done
-
-# correct absolute symlinks
-APPDIR=${APPDIR} $(dirname $0)/fixlinks
+find ${APPDIR} -type d -name "desktop" -exec cp \{\}/icons/small/armagetronad.png ${APPDIR}/${PACKAGE}.png \;
 
 lastpath=
-otherpath=
 
 function copylib()
 {
@@ -25,21 +18,21 @@ function copylib()
     path=$(dirname ${baselib})
     baselib=$(basename ${baselib})
     echo "Found in ${path}."
-    if test "$lastpath" != "$path"; then
-        otherpath=$lastpath
+    if test -n "$lastpath" && test "$lastpath" != "$path"; then
+        echo "error: different paths detected, frankenbuild!"
+        exit 1
     fi
     lastpath=$path
     while test -n "${baselib}"; do
       # copy libary
       echo Copying ${baselib}...
-      cp -ax "${path}/${baselib}" ${APPDIR}/usr/lib/
+      cp -ax "${path}/${baselib}" ${APPDIR}/usr/local/lib/
       # resolve links
       baselib=$(ls -l ${path}/${baselib} | grep -- "->" | sed -e "s,.*-> ,,")
     done
 }
 
 #   include libraries
-mkdir -p ${APPDIR}/usr/lib/
 mkdir -p ${APPDIR}/usr/local/lib/
 for library in \
 libxml2 \
@@ -56,24 +49,18 @@ libSDL_image libpng \
   fi
 done
 
-if ! echo ${PACKAGE} | grep dedicated; then
-# libraries we know are dynamically loaded later, so they don't appear in ldd's output
 for library in \
 libjpeg.so.62 \
 ; do
     echo "Installing library ${library} anyway, we know it's needed."
-    if test -r ${lastpath}/${library}; then
-        copylib ${lastpath}/${library}
-    else
-        copylib ${otherpath}/${library}
-    fi
+    copylib ${lastpath}/${library}
 done
-fi
+
 
 echo $lastpath
 
 #   and pack it up. The script is stupidly only available inside a portable app
 #   called AppImageAssistant; fetch it and extract it with AppImageExtractor
 #   to /usr/local/bin/.
-rm -f ${PORTABLE}
-/usr/local/bin/AppImageAssistant.AppDir/package ${APPDIR} ${PORTABLE}
+rm -f ${PORTABLE_CLIENT}
+/usr/local/bin/AppImageAssistant.AppDir/package ${APPDIR} ${PORTABLE_CLIENT}
